language: node_js

# https://github.com/nodejs/LTS
node_js:
  - '10'
  - '12'
  - '14'

git:
  depth: 5

cache: yarn

before_install:
  - npm config set spin false --global

script:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then npm run prettier:check && npm run lint && npm run check && npm run cover:lcov; else npm run testonly; fi

after_success:
  - if [[ "$TRAVIS_JOB_NUMBER" == *.1 ]]; then cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js; fi
